-- SETUP INICIAL DO SUPABASE - FIBRASIL V2
-- Execute este script na aba "SQL Editor" do Supabase do novo projeto.

-- 1. Tabela PERFIS (Relacionada aos Usuários da Autenticação)
create table public.perfis (
  id uuid references auth.users(id) on delete cascade not null primary key,
  nome text,
  email text,
  role text default 'usuario', -- admin_master, admin, editor, usuario
  ativo boolean default true,
  criado_em timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ativa o RLS na tabela de Perfis
alter table public.perfis enable row level security;

-- Políticas (RLS) para Perfis:
-- Todo usuário autenticado pode ler os perfis básicos
create policy "Usuários podem ver perfis" 
on public.perfis for select 
to authenticated 
using (true);

-- Apenas admins podem alterar perfis
create policy "Admins podem atualizar perfis" 
on public.perfis for update 
to authenticated 
using ((select role from public.perfis where id = auth.uid()) in ('admin', 'admin_master'));

-- Trigger para criar perfil automaticamente ao registrar no Auth
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.perfis (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. Tabela TICKETS
create table public.tickets (
  id bigint generated by default as identity primary key,
  ttk text not null,
  id_servico text,
  sp text,
  regiao text,
  grupo_regiao text default 'SUL',
  data_inicio timestamp with time zone,
  cidade text,
  sigla text,
  tag text not null,
  atualizado_em timestamp with time zone,
  atualizado_por text
);

-- Ativa RLS nos Tickets
alter table public.tickets enable row level security;

-- Políticas (RLS) para Tickets:
create policy "Leitura para todos autenticados" 
on public.tickets for select to authenticated using (true);

create policy "Inserção para autenticados" 
on public.tickets for insert to authenticated with check (true);

create policy "Atualização para autenticados" 
on public.tickets for update to authenticated using (true);

create policy "Deleção para autenticados" 
on public.tickets for delete to authenticated using (true);


-- 3. Tabela LOGS
create table public.logs (
  id bigint generated by default as identity primary key,
  acao text not null,
  ttk text,
  detalhe text,
  usuario text,
  criado_em timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ativa RLS nos Logs
alter table public.logs enable row level security;

-- Políticas para Logs
create policy "Log inserção para autenticados" 
on public.logs for insert to authenticated with check (true);

create policy "Apenas admin_master deleta logs"
on public.logs for delete to authenticated 
using ((select role from public.perfis where id = auth.uid()) = 'admin_master');


-- 4. ATIVAR REALTIME NA TABELA TICKETS
-- Habilita a escuta de modificações ao vivo (Insert/Update/Delete) para a tela do Painel
alter publication supabase_realtime add table public.tickets;
